### ISSUE TITLE
NoneType' object has no attribute 'tzinfo'

### ISSUE THREAD

**Issue by danlipsa** [opendatacube/eo-datasets#118]
I am trying to use eo-datasets to generate a dataset document, and then load that data using datacube. 
I use the devel branches from both eo-datasets and datacube-core.

I use the following script to generate the dataset document:

<pre>
from eodatasets3 import DatasetAssembler
from datetime import datetime
from pathlib import Path

lc8 = Path('/home/danlipsa/data/iarpa_smart_sampledata/LC08_L1GT_044034_20130330_20170310_01_T2')
[blue_geotiff_path] = lc8.rglob("L*_B2.TIF")
out = Path(blue_geotiff_path.parent / Path(blue_geotiff_path.stem + '.yaml'))
print("Out: {}", out)

with DatasetAssembler(metadata_path=out) as p:
  p.datetime = datetime(2019, 7, 4, 13, 7, 5)
  p.product_family = "landsat8_example_product"
  p.properties["odc:file_format"] = "GeoTIFF"
  p.processed_now()

  # Note the measurement in the metadata. (instead of ``write``)
  p.note_measurement('blue', blue_geotiff_path,
                     relative_to_dataset_location=True)

  p.done()
</pre>

which results in the following yaml file:

<pre>
---
# Dataset
$schema: https://schemas.opendatacube.org/dataset
id: 2828e23a-8501-43ca-9449-fa7427e49614

label: landsat8_example_product_2019-07-04
product:
  name: landsat8_example_product

crs: epsg:32610
geometry:
  type: Polygon
  coordinates: [[[374895.0, 4258485.0], [332775.0, 4080195.0], [334387.96078400686,
        4079775.8375337427], [514935.0, 4036365.0], [515054.10427500436, 4036717.7239312488],
      [515804.18418644054, 4039868.051384181], [534524.1924086247, 4118768.0860084835],
      [557466.2132034355, 4216026.213203436], [556671.7954048398, 4216244.220240811],
      [374895.0, 4258485.0]]]
grids:
  default:
    shape: [7421, 7511]
    transform: [30.0, 0.0, 332385.0, 0.0, -30.0, 4258815.0, 0.0, 0.0, 1.0]

properties:
  datetime: 2019-07-04 13:07:05Z
  odc:file_format: GeoTIFF
  odc:product_family: landsat8_example_product

image:
  bands:
    'blue':
      path: LC08_L1GT_044034_20130330_20170310_01_T2_B2.TIF

accessories: {}

lineage: {}
...
</pre>

Note that I had to replace 
<pre>
measurements:
  blue:
</pre>
with
<pre>
image:
  bands:
    'blue':
</pre>
Otherwise the dataset does not get added to datacube. After this I can add both the product and the dataset to datacube.
Here is the product:
<pre>
name: landsat8_example_product
description: Landsat 8 example product
metadata_type: eo

metadata:
    product:
        name: landsat8_example_product
    # Alternatively, include specific items to match
    # properties:
        # eo:instrument: OLI_TIRS
        # eo:platform: landsat-8

measurements:
    - name: 'blue'
      aliases: [band_2, sr_band2]
      dtype: int16
      nodata: -9999
      units: 'reflectance'
</pre>

I try to show the image using datacube using the following script:
<pre>
import datacube
import matplotlib.pyplot as plt

dc = datacube.Datacube(app='plot-rgb-recipe')
print(dc.list_products())
print(dc.list_measurements())

query = {
    'lat': (36.46, 38.46),
    'lon': (-124.92, -122.35)
}

data = dc.load(product='landsat8_example_product', measurements=['blue'], resolution=(-30, 30), output_crs="EPSG:32610")
print(data.data_vars['blue'])
data.data_vars['blue'].plot()
plt.show()
</pre>

however I get the following error:
<pre>
env) [~/tasks/datacube]$ python show-result-assembler.py 
                        name                description   lon   lat  time format platform creation_time label instrument product_type  crs  resolution  tile_size  spatial_dimensions
id                                                                                                                                                                                   
1   landsat8_example_product  Landsat 8 example product  None  None  None   None     None          None  None       None         None  NaN         NaN        NaN                 NaN
----------------------------------------------------------------------
                                      name  dtype        units  nodata             aliases
product                  measurement                                                      
landsat8_example_product blue         blue  int16  reflectance   -9999  [band_2, sr_band2]
Traceback (most recent call last):
  File "show-result-assembler.py", line 14, in <module>
    data = dc.load(product='landsat8_example_product', measurements=['blue'], resolution=(-30, 30), output_crs="EPSG:32610")
  File "/home/danlipsa/projects/datacube-core/env/lib/python3.8/site-packages/datacube/api/core.py", line 315, in load
    grouped = self.group_datasets(datasets, group_by)
  File "/home/danlipsa/projects/datacube-core/env/lib/python3.8/site-packages/datacube/api/core.py", line 404, in group_datasets
    datasets = sorted(datasets, key=group_func)
  File "/home/danlipsa/projects/datacube-core/env/lib/python3.8/site-packages/datacube/api/query.py", line 153, in _extract_time_from_ds
    return normalise_dt(ds.center_time)
  File "/home/danlipsa/projects/datacube-core/env/lib/python3.8/site-packages/datacube/utils/dates.py", line 109, in normalise_dt
    if dt.tzinfo is not None:
AttributeError: 'NoneType' object has no attribute 'tzinfo'
</pre>

Any suggestions of what am I doing wrong? Thanks!

**Comment by alexgleith** [comment]
Hey mate, you should NOT need to change the EO Datasets document.

One thing I notice is you have an `eo` product type definition, whereas EO Datasets will be creating a `eo3` type. I recommend you update your product definition to EO3.

We have some example EO3 product definitions here: https://github.com/GeoscienceAustralia/digitalearthau/tree/develop/digitalearthau/config/eo3/products-aws

**Comment by danlipsa** [comment]
> One thing I notice is you have an eo product type definition, whereas EO Datasets will be creating a eo3 type. I recommend you > update your product definition to EO3.

Thank you! That was the problem! I think I got an error complaining that datacube does not know about eo3 and I changed it to eo. Not sure how I got that. Maybe I did not install the devel version of datacube-core.

Just to confirm: eo3 works with the devel version of datacube-core (datacube --version
Open Data Cube core, version 1.8.4.dev52+g07bc51a5)?

**Comment by danlipsa** [comment]
Does it work with older releases of datacube?

**Comment by jeremyh** [comment]
Any datacube from 1.8 onwards "natively" supports the eo3 format. On older releases, you can use the indexing commands in [odc-tools](https://github.com/opendatacube/odc-tools) which can convert eo3 on the fly.

But I don't think you're missing datacube compatibility, you're missing an eo3 metadata type in your datacube instance. ODC adds some default metadata types automatically to new datacubes, but won't add them to existing datacubes, and I'm guessing yours predated datacube 1.8 before eo3 was included by default.

You should be able to add it like so:

```bash
datacube metadata add https://raw.githubusercontent.com/GeoscienceAustralia/digitalearthau/develop/digitalearthau/config/eo3/eo3.odc-type.yaml
```

 (this is one of the more confusing parts of datacube: metadata types tell ODC what metadata fields matter in your document. `eo3` is a plain default one for the eo3 format, but in other environments we add extra fields for custom metadata.)

**Comment by danlipsa** [comment]
Great, thank you very much!
