### ISSUE TITLE
Add support for retrieving a  `DatasetDoc` from `DatasetAssembler`

### ISSUE THREAD

**Issue by kieranricardo** [opendatacube/eo-datasets#128]
I'd like to add support for getting a `DatasetDoc` from `DatasetAssembler`. Maybe this could be done with something as simple as:

```python
class DatasetAssembler:
     ...
    def done(..., write_metadata=True): # option to not write metadata to file
        ....
        self.dataset = DatasetDoc(...) # store dataset for user retrieva

```

What do you reckon @jeremyh?

**Comment by jeremyh** [comment]
That sounds like a good idea to me.

We have a few tasks now that are in the realm of "allow calculated information to be read back from assembler". I'd like to play with the API a little to make sure we can do them all friendly and consistent.
