### ISSUE TITLE
Can't use custom `eo:platform` metadata value

### ISSUE THREAD

**Issue by valpesendorfer** [opendatacube/eo-datasets#132]
I'm trying to create `eo3` dataset metadata for some MODIS data with the `DatasetAssembler`, and I'd like to include whether the data is from Terra or Aqua. The best fit in the metadata definition I've found is the `eo:platform` property.

But when I try to pass in a platform code, I get a `NotImplementedError`, raised in:

https://github.com/GeoscienceAustralia/eo-datasets/blob/e07a3e87e6d6990ef3a6045784930bbb49455bfd/eodatasets3/model.py#L337

and likely also in

https://github.com/GeoscienceAustralia/eo-datasets/blob/e07a3e87e6d6990ef3a6045784930bbb49455bfd/eodatasets3/model.py#L356

meaning I can't use any platform name that doesn't start with `sentinel-1`, `sentinel-2` or `landsat`. 

Is there any reason the `DatasetAssembler` can't just use the user defined platform code if it doesn't match S1/S2/LS ?

**Comment by jeremyh** [comment]
Thanks for the report @valpesendorfer .

In develop, built-in abbreviations are now extensible.

You can also [set abbreviations manually](https://eodatasets.readthedocs.io/en/latest/#eodatasets3.DatasetPrepare.names):
```python
p.names.platform_abbreviated = "ls"
p.names.instrument_abbreviated = "e"
```
