### ISSUE TITLE
Include property 'providers'

### ISSUE THREAD

**Issue by JonDHo** [opendatacube/eo-datasets#187]
Hello! The property 'providers' does not appear to be in the KNOWN_STAC_PROPERTIES list,
but I believe it to be valid.

An example value of this property is: 
```json
[
   {
      "name":"Remote Data, Inc",
      "description":"Producers of awesome spatiotemporal assets",
      "roles":[
         "producer",
         "processor"
      ],
      "url":"http://remotedata.it"
   }
]
```

See: 
- https://github.com/radiantearth/stac-spec/blob/master/item-spec/common-metadata.md#provider and
- https://github.com/radiantearth/stac-spec/blob/789e90fba4c7119bc925d26f75f47bacf44c91e6/examples/collectionless-item.json#L51

Thank you!

**Comment by jeremyh** [comment]
Thanks @JonDHo! added in #191
