### ISSUE TITLE
update packaging for GA Landsat NBAR and NBAR-T

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/eo-datasets#19]
yaml format metadata is now part of production NBAR-T - updates are required to support packaging for NBAR-T

see examples here:

/g/data/v10/testing_ground/nbar-tc/2015-10/output/LS8_OLITIRS_NBAR_P51_GALPGS01-032_115_079_20151001/nbar-metadata.yml

We are targeting both NBAR and NBAR-T products
Eg. /g/data/v10/testing_ground/nbar-tc/2015-10/output/LS8_OLITIRS_NBAR_P51_GALPGS01-032_115_079_20151001/Reflectance_Outputs/
NBAR = reflectance_brdf_X.bin
NBAR-T = reflectance_terrain_X.bin

The ultimate aim is to have the data packaged and ingested to enable production of our first NBAR-T mosaic.

**Comment by jeremyh** [comment]
Class `NbarDriver` in `eodatasets/drivers.py` packages the Josh's previous outputs -- I imagine we just need to expand the `fill_metadata()` method with Josh's new metadata info. 

Run it similiarly to the example in the eodatasets readme, but calling the nbar driver (and giving the source ortho):

```
$ eod-package nbar_terrain --parent /data/packages/LS8_ORTHO.. \
      joshs_output/Reflectance_Outputs/ packages/
```

**Comment by jeremyh** [comment]
It also sounds like we want to revise some of the codes it uses (no packages have been output, so we can still change these). 

Currently it uses:
- `'TNBAR'` and `'NBAR'` for product codes. 
- `'nbar_terrain'` and `'nbar_brdf'` for driver names.

But `'NBART'` seems to have become the standard term over `'TNBAR'`.
