### ISSUE TITLE
Add polygon boundary to ga-metadata.yml for NBAR/T and PQ

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/eo-datasets#22]
simplified json format generalised bounding box with 1 pixel buffer appended to yaml metadata as per @sixy6e example - addresses https://github.com/data-cube/agdc-v2/issues/121

**Comment by omad** [comment]
See https://gist.github.com/v0lat1le/2a6f134ae21b7c98ef34cf099aef9cb4 for example code.

**Comment by omad** [comment]
Implemented as of 5cb4fd88fe.

I've tested with a single real PQ dataset, but couldn't find any unpackaged NBAR data to test on. I also had trouble getting **gaip** running to produce some.

**Comment by omad** [comment]
An example PQ `ga-metadata.yaml` is at `/short/v10/dra547/pqa2/LS5_TM_PQ_P55_GAPQ01-002_096_076_20110102/ga-metadata.yaml`. it includes a polygon boundary under `grid_spatial -> projection -> valid_data`.

It was produced by running eo-datasets manually, and so doesn't include the updated software versions metadata, which requires changes in `gaip`, which have been made but not yet deployed.

**Comment by omad** [comment]
Old, seems to be resolved.
