### ISSUE TITLE
conflicting dependencies on conda

### ISSUE THREAD

**Issue by nikkopante** [opendatacube/eo-datasets#224]
I want to install eodatasets3 in a conda environment. However there are conflicting dependency with rasterio.

```
ERROR: Cannot install eodatasets3==0.1.0, eodatasets3==0.10.0, eodatasets3==0.10.1, eodatasets3==0.11.0, eodatasets3==0.12.0, eodatasets3==0.13.0, eodatasets3==0.14.0, eodatasets3==0.14.1, eodatasets3==0.14.2, eodatasets3==0.15.0, eodatasets3==0.15.1, eodatasets3==0.16.0, eodatasets3==0.17.0, eodatasets3==0.17.1, eodatasets3==0.18.0, eodatasets3==0.19.0, eodatasets3==0.19.1, eodatasets3==0.19.2, eodatasets3==0.19.3, eodatasets3==0.2.0, eodatasets3==0.20.0, eodatasets3==0.20.1, eodatasets3==0.21.0, eodatasets3==0.21.1, eodatasets3==0.22.0, eodatasets3==0.22.1, eodatasets3==0.22.2, eodatasets3==0.23.0, eodatasets3==0.23.1, eodatasets3==0.24.0, eodatasets3==0.24.1, eodatasets3==0.3.0, eodatasets3==0.4.0, eodatasets3==0.5.0, eodatasets3==0.6.0, eodatasets3==0.7.0, eodatasets3==0.8.0, eodatasets3==0.9.0, eodatasets3==0.9.1, eodatasets3==0.9.2 and eodatasets3==0.9.3 because these package versions have conflicting dependencies.
```

I created the environment using:
`conda create -n eo3 pip`

then installed it using pip
`pip install eodatasets3`

I am using Windows 10

**Comment by jeremyh** [comment]
Hi Nikko. Was there more output in the error? It may have said which dependency is causing it.

If you're using conda, it's best to use it's own packages for libraries as much as possible. Installing those first might fix the issue.

Try: conda install `datacube pyproj affine numpy scipy shapely`  into your environment before you pip install eodatasets again.

**Comment by omad** [comment]
[eodatasets3 is available from conda-forge](https://anaconda.org/conda-forge/eodatasets3) now, so this has been resolved.
