### ISSUE TITLE
Add TIRS SSM model for Landsat 8 to the Level 1 packaged metadata

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/eo-datasets#24]
One additional ancillary source needs to be added in the yaml file for LS8 product from the main LPGS log file (landsat-processor.log)

ga-metadata.yaml:
……
ancillary_quality: DEFINITIVE
ancillary:
        cpf:
            ……………………..
            access_dt: 2016-05-18 18:13:19
            modification_dt: 2014-11-26 13:03:32
            checksum_sha1: b59e3585757e2a09937a7b8482786c205354807e
       ssm:
            name: xxxxxxx
            uri: /g/data/v10/eoancillarydata/sensor-specific/LANDSAT8/TIRS-SSM/xxxxxxxxx
            …….
And, how do you define the field “ancillary_quality” – I assume that if all ancillary = definitive, then DEFINITIVE?

In LS8 case, ssm may not be DEFINITIVE. We could add “TIRS_SSM_MODEL” (from MTL) in yaml file. If TIRS_SSM_MODEL  =  Preliminary, then ancillary_quality is not DEFINITIVE.

ga-metadata.yaml:
……
ancillary_quality: DEFINITIVE
ancillary:
        cpf:
            ……………………..
            access_dt: 2016-05-18 18:13:19
            modification_dt: 2014-11-26 13:03:32
            checksum_sha1: b59e3585757e2a09937a7b8482786c205354807e
       ssm:
            name: xxxxxxx
            uri: /g/data/v10/eoancillarydata/sensor-specific/LANDSAT8/TIRS-SSM/xxxxxxxxx

And, how do you define the field “ancillary_quality” – I assume that if all ancillary = definitive, then DEFINITIVE?

In LS8 case, ssm may not be DEFINITIVE. We could add “TIRS_SSM_MODEL” (from MTL) in yaml file. If TIRS_SSM_MODEL  =  Preliminary, then ancillary_quality is not DEFINITIVE.

**Comment by jeremyh** [comment]
I'm increasingly thinking a single 'ancillary_quality' value is too inflexible, and prone to problems as more types are added in the future (such as this TIRS SSM). 

I've instead recorded quality against each ancillary record individually, so that we can decide lazily how to classify the quality as a whole. That existing quality field will still exist in LS5/7 for backwards compatibility, though.

Sound ok?

**Comment by simonaoliver** [comment]
Sounds good

**Comment by jeremyh** [comment]
Implemented in 00d98c9f28dc07e18560f2e10d0d09a61517e980, 84aa8dbd519005eb8a37ac1e91c646cdfd9e87d8, fb85600ef8d0872b06e0aebb98f9fdc626522ada
