### ISSUE TITLE
Issue with paths containing special characters

### ISSUE THREAD

**Issue by clausmichele** [opendatacube/eo-datasets#262]
Hi everyone! At EURAC Research our home directory is named with our email address which contains the @ character.

When I try to use ` DatasetPrepare(metadata_path=metadata_path,allow_absolute_paths=True)` it fails due to my path format.
`metadata_path = /home/user@eurac.edu/DATACUBES/ado_spei_1_era5_qm_odc`

I've tracked down the problem:
1. The absolute path is converted into an URI, which replaces the special characters (@ -> %40) in resolve_location() https://github.com/opendatacube/eo-datasets/blob/14b075a94b80e8a929de8b293999a10939c756c2/eodatasets3/names.py#L454
2. Later on, when this URI is being used to create a directory using pathlib, it fails.

Sampel code to reproduce the issue:
```python
import pathlib
path = pathlib.Path('special@folder')
path.mkdir()
path2 = pathlib.Path('special%40folder/test')
path2.mkdir()
>>>Traceback (most recent call last):
>>>  File "<stdin>", line 1, in <module>
>>>  File "/home/mclaus@eurac.edu/anaconda3/envs/odc38/lib/python3.8/pathlib.py", line 1288, in mkdir
>>>    self._accessor.mkdir(self, mode)
>>>FileNotFoundError: [Errno 2] No such file or directory: 'special%40folder/test'
path2 = pathlib.Path('special@folder/test')
path2.mkdir()
```

**Comment by omad** [comment]
Thanks for the report Claus. It looks like an easy case to reproduce, hopefully a fix isn't too difficult either...
