### ISSUE TITLE
EO3 dataset schema does not allow uppercase measurement names, while ODC core does

### ISSUE THREAD

**Issue by tijmenr** [opendatacube/eo-datasets#268]
The dataset schema of EO3 (https://github.com/opendatacube/eo-datasets/blob/eodatasets3-0.29.0/eodatasets3/dataset.schema.yaml#L89) only allows for lowercase measurement names. ODC core is does not have this restriction (https://github.com/opendatacube/datacube-core/blob/develop/datacube/model/schema/dataset-type-schema.yaml#L94), and some standard product configurations in ODC do use uppercase names, e.g. https://github.com/opendatacube/datacube-dataset-config/blob/main/products/s2_l2a.odc-product.yaml.

This causes issues when converting a dataset retrieved from ODC into an EO3 metadata document (e.g. to use it as a source for properties or lineage):

```python
(ds, *_) = odc.find_datasets(product='s2_l2a', ...)
import eodatasets3 as eo3
eo3.serialise.from_doc(doc=ds.metadata_doc)
=>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/odc_env/lib/python3.10/site-packages/eodatasets3/serialise.py", line 206, in from_doc
    DATASET_SCHEMA.validate(doc)
  File "/opt/odc_env/lib/python3.10/site-packages/jsonschema/validators.py", line 267, in validate
    raise error
jsonschema.exceptions.ValidationError: 'AOT' does not match '^[a-z_][a-z0-9_]*$'

Failed validating 'pattern' in schema['properties']['measurements']['propertyNames']:
    {'pattern': '^[a-z_][a-z0-9_]*$'}

On instance['measurements']:
    'AOT'
```

A workaround is to completely skip schema validation (`from_doc(..., skip_validation=True)`, but it would be nice if there was consistency between the different opendatacube projects.

**Comment by tijmenr** [comment]
Additionally, trying to convert a dataset (retrieved from ODC) that does not have uppercase names, also fails because the ODC metadata doc contains properties 'extent' and 'grid_spatial' that are not conform the EO3 schema:

```python
ds = odc.index.datasets.get('...')
eo3.serialise.from_doc(doc=ds.metadata_doc, skip_validation=False)
=>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/odc_env/lib/python3.10/site-packages/eodatasets3/serialise.py", line 206, in from_doc
    DATASET_SCHEMA.validate(doc)
  File "/opt/odc_env/lib/python3.10/site-packages/jsonschema/validators.py", line 267, in validate
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('extent', 'grid_spatial' were unexpected)

Failed validating 'additionalProperties' in schema:
...
```

So, maybe my more generic question is: What is the general way to use a datacube.Dataset as input for eodatasets3.assemble.DatasetPrepare.add_source_dataset() ?

**Comment by jeremyh** [comment]
Thanks for the report. We did standardise on lowercase ourselves... but if ODC allows it we probably should too.

(at worst, we could make it a warning from eo3-validate rather than an error)
