### ISSUE TITLE
Enforce consistency of Naming Conventions (e.g. GeoTiff/GeoTIFF)

### ISSUE THREAD

**Issue by ASVincent** [opendatacube/eo-datasets#27]
Eo-datasets currently uses both GeoTiff and GeoTIFF internally as defaults, it should be brought into some kind of alignment internally.

If there is a requirement to support both (for historical reasons) this should be configurable at run-time.

**Comment by jeremyh** [comment]
Note that the metadata class should convert all of them to "GeoTIFF", see here:
https://github.com/GeoscienceAustralia/eo-datasets/blob/968307311ff87f947c7b1c400285254a58ce8a2b/eodatasets/type.py#L247



Which is used when initialising a `FormatName` field: https://github.com/GeoscienceAustralia/eo-datasets/blob/968307311ff87f947c7b1c400285254a58ce8a2b/eodatasets/type.py#L210

As far as I can see, all other variants of capitalisation are on construction of `FormatName()`s (particulary during tests). The tests themselves will fail if another capitalisation is output in a package.

(The choice of `GeoTIFF` is not particular pretty, but predates the use of eodatasets: it was chosen for consistency with the legacy systems)

**Comment by omad** [comment]
`GeoTIFF` is the preferred capitalisation, see [google search results for 'geotiff'](https://www.google.com/search?q=geotiff).

The production database currently has a mismatch between product/dataset (GeoTiff/GeoTIFF respectively). Which I'm going to fix by changing everything to `GeoTIFF`.

**Comment by ASVincent** [comment]
Fixed
