### ISSUE TITLE
dataset maturity properties

### ISSUE THREAD

**Issue by Ariana-B** [opendatacube/eo-datasets#272]
Hi @jeremyh,
With a view to implementing dataset maturity for the s2 ard upgrade, would it make sense for `dea:dataset_maturity` and `dea:product_maturity` to be included in the list of inheritable properties or would they be irrelevant in certain scenarios?

**Comment by omad** [comment]
It definitely makes sense for `dea:dataset_maturity`. I don't think it does for `dea:product_maturity`.

Product maturity isn't really meant to be handled here.
