### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by omad** [opendatacube/eo-datasets#39]
Running the command `pip install .` from within a Windows `conda` environment fails with the error:
```
Processing c:\users\u68320\pycharmprojects\eo-datasets
Could not install packages due to an EnvironmentError: [('C:\\Users\\u68320\\PycharmProjects\\eo-datasets\\tests\\integration\\input\\npp-viirs\\data\\NPP_VIIRS_STD-RDR_P00_NPP.VIIRS.18966.ALICE_0_0_20150626T053709Z20150626T054942_1\\RNSCA-RVIRS_npp_d20150626_t0537097_e0549423_b18966_c20150626055046759000_nfts_drl.h5', 'C:\\Users\\u68320\\AppData\\Local\\Temp\\pip-req-build-mkb3dieh\\tests\\integration\\input\\npp-viirs\\data\\NPP_VIIRS_STD-RDR_P00_NPP.VIIRS.18966.ALICE_0_0_20150626T053709Z20150626T054942_1\\RNSCA-RVIRS_npp_d20150626_t0537097_e0549423_b18966_c20150626055046759000_nfts_drl.h5', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\u68320\\\\AppData\\\\Local\\\\Temp\\\\pip-req-build-mkb3dieh\\\\tests\\\\integration\\\\input\\\\npp-viirs\\\\data\\\\NPP_VIIRS_STD-RDR_P00_NPP.VIIRS.18966.ALICE_0_0_20150626T053709Z20150626T054942_1\\\\RNSCA-RVIRS_npp_d20150626_t0537097_e0549423_b18966_c20150626055046759000_nfts_drl.h5'")]
```

The `no such file` error path is 276 characters long. If I run `set TMP=C:\tmp` and `set TEMP=C:\tmp` first, the install succeeds. Windows doesn't like long file names. :(

Perhaps it would be possible to shorten the test data file names a bit to work around this.

**Comment by jeremyh** [comment]
Fixed in eodatasets3 by removing them --- those datasets are part of the GA's old-old collection and are no longer relevant to us.

**Comment by jeremyh** [comment]
For now `eodatasets` and `eodatasets3` are installed side-by-side as they're not feature compatible and some repos are using the old one. I can backport the "fix" if needed.
