### ISSUE TITLE
Setting processed time to "now" is error-prone for users

### ISSUE THREAD

**Issue by jeremyh** [opendatacube/eo-datasets#47]
It's easy to set processing time like this:
```
p.processed = datetime.now()
```

But that's wrong! The date has no timezone, so the assembler will assume it's in UTC. 

This is technically the users' fault but is an easy mistake to make. Ideally the api should make this mistake less easy.

Our fields use UTC by default because almost every metadata format we read from has dates in UTC (without any timezone).

Some options:
- Warn when there's no timezone, so the user wants to include one explicitly.
- Add UTC to the parameter name `p.processed_utc = ...`
- Add a "p.processed_now()` function that fills it in for you. This could perhaps fill-in other host information too.

**Comment by omad** [comment]
I like the option of `p.processed_now()`.

I'd also make setting a non-timezoned date onto `p.processed` an error, not a warning. It's a code problem and in many senses a pretty bad one since it's invisible.

`p.processed_utc = ...` seems more confusing.

**Comment by jeremyh** [comment]
Added `processed_now()`. I'm undecided about the others as I'm worried about making the common case more complicated...
