### ISSUE TITLE
Need additional instructions on setting up to perform development

### ISSUE THREAD

**Issue by whatnick** [opendatacube/eo-datasets#65]
Using current instructions pytest fails with missing imports. Additional steps are needed for pytest to work smoothly ( assumes conda is used to allow pre-compiled GDAL) : 
- pip install -e .
- pip install -e .[test]
- conda install gdal
- export GDAL_DATA = "where GDAL_DATA went"
- pip install eodatasets3[ancillary]
- pip install h5py

As of 16/12/2019 running pytest here has the following result:
```
=== 2 failed, 91 passed, 25 warnings in 7.57s ===
```

against origin/HEAD

**Comment by jeremyh** [comment]
Thanks Tisham!

Those other optional dependencies are installable in one step with `pip install -e .[all]`

But it's a mistake that they're not included with the `[test]` group, since there's tests on the optional parts too.

**Comment by jeremyh** [comment]
In that PR, the travis build now does the same thing we say in our docs: just a `pip install -e .[test]`

**Comment by jeremyh** [comment]
You also mentioned test failures, do you still get them? Which tests? 

They're passing on Travis and locally for me.

**Comment by jeremyh** [comment]
When running on gdal 3 exactly two tests failed -- my guess is that that was the problem you saw. Gdal 3 is now the default in some environments.

I've added a fix for gdal 3 to my PR. Feel free to reopen this if your failures still occur.
