### ISSUE TITLE
Writing metadata only

### ISSUE THREAD

**Issue by EmilienAlvarez** [opendatacube/eo-datasets#79]
Hello,
I want to create a datacube metadata index with absolute paths because my data are stored on another hard-drive. But when i try to write only metadata in a folder outside my data folder it doesn't work and it doesn't work neither when i try it in the same data folder, i have to write data too.
I have this error : 
```
f"Path {value.as_posix()!r} is outside path {base_directory.as_posix()!r} "
ValueError: Path '/mnt/data/imagery/sentinel-2/SENTINEL2A_20180517-111020-570_L2A_T30UXU_D_V1-7/SENTINEL2A_20180517-111020-570_L2A_T30UXU_D_V1-7_FRE_B11.tif' is outside path '/home/alvarez_e/ODC' (allow_paths_outside_base=False)
```
It isn't possible to turn True `allow_paths_outside_base` in `make_paths_relative()` ?

**Comment by jeremyh** [comment]
Thanks for the report @EmilienAlvarez,

In the develop version you can now [embed locations](https://eodatasets.readthedocs.io/en/latest/#separating-metadata-from-data) to store data separately.

There's also now a metadata-only [DatasetPrepare](https://eodatasets.readthedocs.io/en/latest/#writing-only-a-metadata-doc) api, and support for flag `allow_absolute_paths=True` if you do want absolute paths.

Closing -- feel free to reopen if there's issues.
