### ISSUE TITLE
Excessive memory usage in NCI jobs

### ISSUE THREAD

**Issue by sixy6e** [opendatacube/eo-datasets#81]
On monitored systems such as NCI, the reported memory usage includes any cached objects.  GDAL defaults to using 5% of the available memory.

One suggestion would be to tile the I/O rather than read the whole image at once into memory. This would enable processing of images larger than the available memory, but would require some time to rewrite.  Unfortunately, time is not on our side so this approach will have to wait.

A quicker solution for the short term is to change the _GDAL_CACHEMAX_ environment.  This can be done temporarily at the time of opening any imagery by:

```python
with rasterio.Env(GDAL_CACHEMAX=64):
    with rasterio.open(<filename>) as src:
        # do stuff
```

Where `64` indicates 64MB.

**Comment by Oceancolour-RG** [comment]
Initial tests with rasterio.Env(GDAL_CACHEMAX=64) are encouraging. I'm more than happy to contribute

**Comment by jeremyh** [comment]
Gdal cache size was was reduced in other PRs, closing.
